### PR TITLE
Output result as data

### LINKED ISSUE #70: process does not exit after catching error
The process keeps active and the temp folder is not removed when an error js thrown. 
When an error is thrown, the output should be informative to the user. Now the stacktrace is dumped in the console.

### PR DESCRIPTION
**Pull request by petergoes**
The module outputs an object to consuming modules so own reporters can be written. The CLI version should als use this data instead of the `parser-stats` module. However, to keep this PR small. That is a done in its own PR (not started as of the time of this writing)

To test this PR, replace the current `.then` in `bin/fastatic` with:

```
.then(output => {
    console.log('src:')
    Object.keys(output.fileSize.src).map(key => {
        console.log(' ', key, filesize(output.fileSize.src[key]))
    })
    console.log('dest:')
    Object.keys(output.fileSize.dest).map(key => {
        console.log(' ', key, filesize(output.fileSize.dest[key]))
    })
    console.log('output:');
    console.log(output);
})
```

closes #70 (and supersedes #75)

### CODE REVIEW

**Comment by petergoes** [comment]
@jbmoelker I split the module up and return a new object as discussed

File: index.js [hunk 1]
```diff
@@ -14,17 +16,26 @@ function fastatic(options) {
 	loader.setSpinnerString(18);
 	loader.start();
 
-	const logger = new Logger(config.logLevel);
+	const result = copy(config.src, config.temp)
+		.then(() => parseAll(config))
+		.then(() => stats(config))
+		.then(output => console.log(output))
+		.then(() => loader.stop())
+		.then(() => Promise.all([
```
Comment (jbmoelker) [inline index.js]: I agree this would be the setup if we do more than `compareFileSize`, but without it, I find this overcomplicating the module. So leave out `spread` and instead use:

``` javascript
.then(() => ({
  fileSize: compareFileSize(config.src, config.temp)
});
```

File: lib/compare-file-size.js [hunk 2]
```diff
@@ -0,0 +1,24 @@
+'use strict';
+
+const promisify = require('bluebird').promisify;
+const glob = promisify(require('glob').glob);
+const getFileSizesPerType = require('./get-filesizes-per-type');
+
+function compareFileSize(sourceFolder, tempFolder) {
+	return glob('**/*', { nodir: true, cwd: sourceFolder })
+		.then(files => {
+			const sourceFiles = appendDirToFiles(sourceFolder, files);
```
Comment (jbmoelker) [inline lib/compare-file-size.js]: I'd use `const sourceFiles = files.map(file => path.join(sourceFolder, file));` The function `appendDirToFiles` doesn't instantly tell me what will happen inside. So for a oneline function I find it too much.

File: lib/compare-file-size.js [hunk 3]
```diff
@@ -0,0 +1,24 @@
+'use strict';
+
+const promisify = require('bluebird').promisify;
+const glob = promisify(require('glob').glob);
+const getFileSizesPerType = require('./get-filesizes-per-type');
+
+function compareFileSize(sourceFolder, tempFolder) {
```
Comment (jbmoelker) [inline lib/compare-file-size.js]: this module doesn't need to know about `temp`, and to stick with other vocabulary I would use `(srcDir, destDir)`.

And later also `srcFiles` and `destFiles`. That's why all the way in the end you also return `{ src: ..., dest: ... }`.

File: lib/get-filesizes-per-type.js [hunk 4]
```diff
@@ -0,0 +1,25 @@
+const fs = require('fs');
+const path = require('path');
+
+function getFileSizesPerType(files) {
+	const sizes = getFileSizes(files);
+
+	return files.reduce((typeSizes, file) => {
```
Comment (jbmoelker) [inline lib/get-filesizes-per-type.js]: within this scope you can simplify / shorten your variable names `sizes`, `type`, `size`, `total`. So: `sizes[type] = total + size;` instead of `typeSizes[fileType] = totalForType + fileSize;`.

File: lib/get-filesizes-per-type.js [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+		const fileType = path.extname(file).replace('.', '');
+		const fileSize = sizes[file];
+		const totalForType = typeSizes[fileType] || 0;
```
Comment (jbmoelker) [inline lib/get-filesizes-per-type.js]: Rather `sizes[type] = (sizes[type] || 0) + size;` ?

File: lib/parse-all.js [hunk 6]
```diff
@@ -1,6 +1,7 @@
 'use strict';
-
+const colors = require('colors');
```
Comment (jbmoelker) [inline lib/parse-all.js]: never used

File: lib/parse-all.js [hunk 7]
```diff
@@ -1,6 +1,7 @@
...
 const Deferred = require('./deferred');
+const path = require('path');
```
Comment (jbmoelker) [inline lib/parse-all.js]: never used.

File: lib/parse-all.js [hunk 8]
```diff
@@ -22,7 +23,10 @@ function parseAll(config) {
 					pattern: config.parsers[name].pattern
 				}))
 				.then(res => parsing[name].resolve(res))
-				.catch(err => parsing[name].reject(err));
+				.catch(err => {
+					parsing[name].reject(err);
+					return { name: name, error: err };
```
Comment (jbmoelker) [inline lib/parse-all.js:26]: why do we need to do this?

File: lib/compare-file-size.js (hunk 3 above)
Comment (petergoes) [reply lib/compare-file-size.js]: Although I do agree that term `tempFolder` is wrong, I do think this module needs to know about the two folders. We use it here to compare the file sizes of the source and dest folders, but this module can be used on any two folders. If we were to take out this module and release it on its own, the naming `sourceFolder` and `tempFolder`/`destFolder` are wrong, but I don't know a better naming. Thoughts?

File: lib/parse-all.js (hunk 8 above)
Comment (petergoes) [reply lib/parse-all.js:26]: We need to run all the parsers before we can generate error reporting. this way, we store which parser fails (`name`) and why (`error`)

File: bin/fastatic [hunk 9]
```diff
@@ -11,8 +12,15 @@ const program = require('commander')
...
+
 fastatic({
 	src: program.args[0],
 	dest: program.dest,
 	logLevel: program.logLevel
-});
+})
+.then(config => logger.log('Done. Optimised static files in', config.dest))
+	.catch(err => {
+		console.error(err.message);
```
Comment (jbmoelker) [inline bin/fastatic]: `console.error` => `logger.error`?

File: lib/compare-file-size.js [hunk 10]
```diff
@@ -0,0 +1,20 @@
+'use strict';
+
+const getFileSizesPerType = require('./get-filesizes-per-type');
+const promisify = require('bluebird').promisify;
+const glob = promisify(require('glob').glob);
+const path = require('path');
+
+function compareFileSize(sourceFolder, tempFolder) {
```
Comment (jbmoelker) [inline lib/compare-file-size.js]: I'd still refactor to `srcDir`, `destDir`, `srcFiles` and `destFiles` to be consistent. We've never used "source" or "folder" anywhere.

File: index.js [hunk 11]
```diff
@@ -9,22 +10,27 @@ const stats = require('./lib/parser-stats');
...
+		.then(() => compareFileSize(config.temp.src, config.temp.dest))
+		.then(fileSize => ({fileSize}))
+		.catch(err => {
+			remove(config.temp.root);
+			throw new Error('Optimising failed.');
+		});
 
-	const logger = new Logger(config.logLevel);
+	result
+		.then(() => remove(config.temp.root));
```
Comment (jbmoelker) [inline index.js]: doesn't need a newline

File: lib/parse-all.js [hunk 12]
```diff
@@ -1,5 +1,4 @@
 'use strict';
-
 const Deferred = require('./deferred');
 const parserProgressBar = require('./parser-progress-bar');
```
Comment (jbmoelker) [inline lib/parse-all.js:4]: This PR makes me realise that I think we should refactor the signature of parseAll to `parseAll(cwd, parsers)` and no longer expose all the other config settings to this method. But that's for a separate PR :)

File: index.js [hunk 13]
```diff
@@ -1,3 +1,4 @@
+const compareFileSize = require('./lib/compare-file-size');
```
Comment (jbmoelker) [inline index.js]: missing `)`

File: index.js [hunk 14]
```diff
@@ -9,22 +10,27 @@ const stats = require('./lib/parser-stats');
 
 function fastatic(options) {
 	const config = defineConfig(options);
+	const logger = new Logger(options.logLevel);
 
-	const loader = new Spinner(`%s Crunching ${config.src}`);
-	loader.setSpinnerString(18);
-	loader.start();
+	const result = Promise.all([
```
Comment (jbmoelker) [inline index.js:15]: sorry for the nitpicking, but I think line 16-18 should indent one tab less

File: bin/fastatic [hunk 15]
```diff
@@ -11,8 +12,15 @@ const program = require('commander')
 	.option('-l, --log-level [value]', 'Log level (silent|error|warn|verbose)', 'verbose')
 	.parse(process.argv);
 
+const logger = new Logger(program.logLevel);
+
 fastatic({
```
Comment (jbmoelker) [inline bin/fastatic:17]: more nitpicking: indent line 18-22 with an extra tab?
